FROM nginx

MAINTAINER Crix07

VOLUME C:\Users\Crist\Desktop\SDG_DEMO\angular-app\SDGDEMO\dist\SDGDEMO:/usr/share/nginx/html
# VOLUME /Users/sjobs/Documents/docker-compose-tutorial/angular-app/dist:/usr/share/nginx/html

EXPOSE 80